**PREDICTING FIFA RANKINGS**

# **Importing data libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt

# Loading data sets

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/falaprodavi/Football-Player-Dataset2022/refs/heads/main/datasets/CLEAN_FIFA23_official_data.csv')
df

Unnamed: 0      ID             Name  Age  \
0               0  209658      L. Goretzka   27   
1               1  212198  Bruno Fernandes   27   
2               2  224334         M. Acuña   30   
3               3  192985     K. De Bruyne   31   
4               4  224232       N. Barella   25   
...           ...     ...              ...  ...   
17655       17655  269526    Deng Xiongtao   19   
17656       17656  267946   22 Lim Jun Sub   17   
17657       17657  270567         A. Demir   25   
17658       17658  256624     21 S. Czajor   18   
17659       17659  256376  21 F. Jakobsson   20   

                                                  Photo     Nationality  \
0      https://cdn.sofifa.net/players/209/658/23_60.png         Germany   
1      https://cdn.sofifa.net/players/212/198/23_60.png        Portugal   
2      https://cdn.sofifa.net/players/224/334/23_60.png       Argentina   
3      https://cdn.sofifa.net/players/192/985/23_60.png         Belgium   
4      https://cdn.sofifa.net/players/224/232/23_60.png           Italy   
...                                                 ...             ...   
17655  https://cdn.sofifa.net/players/269/526/23_60.png        China PR   
17656  https://cdn.sofifa.net/players/267/946/22_60.png  Korea Republic   
17657  https://cdn.sofifa.net/players/270/567/23_60.png          Turkey   
17658  https://cdn.sofifa.net/players/256/624/21_60.png          Poland   
17659  https://cdn.sofifa.net/players/256/376/21_60.png          Sweden   

                                      Flag  Overall  Potential  \
0      https://cdn.sofifa.net/flags/de.png       87         88   
1      https://cdn.sofifa.net/flags/pt.png       86         87   
2      https://cdn.sofifa.net/flags/ar.png       85         85   
3      https://cdn.sofifa.net/flags/be.png       91         91   
4      https://cdn.sofifa.net/flags/it.png       86         89   
...                                    ...      ...        ...   
17655  https://cdn.sofifa.net/flags/cn.png       48         61   
17656  https://cdn.sofifa.net/flags/kr.png       48         64   
17657  https://cdn.sofifa.net/flags/tr.png       51         56   
17658  https://cdn.sofifa.net/flags/pl.png       50         65   
17659  https://cdn.sofifa.net/flags/se.png       50         61   

                    Club  ... Position      Joined  Loaned From  \
0      FC Bayern München  ...      SUB  2018-07-01          NaN   
1      Manchester United  ...      LCM  2020-01-30          NaN   
2             Sevilla FC  ...       LB  2020-09-14          NaN   
3        Manchester City  ...      RCM  2015-08-30          NaN   
4                  Inter  ...      RCM  2020-09-01          NaN   
...                  ...  ...      ...         ...          ...   
17655      Meizhou Hakka  ...      RES  2022-04-11          NaN   
17656     Jeju United FC  ...      RES  2022-01-01          NaN   
17657       Ümraniyespor  ...      RES  2021-06-06          NaN   
17658     Fleetwood Town  ...      RES  2020-01-01          NaN   
17659     IFK Norrköping  ...      RES  2020-01-08          NaN   

       Contract Valid Until Height(cm.)  Weight(lbs.)  Release Clause(£)  \
0                    2026.0       189.0       180.810        157000000.0   
1                    2026.0       179.0       152.145        155000000.0   
2                    2024.0       172.0       152.145         97700000.0   
3                    2025.0       181.0       154.350        198900000.0   
4                    2026.0       172.0       149.940        154400000.0   
...                     ...         ...           ...                ...   
17655                2027.0       190.0       171.990           218000.0   
17656                2026.0       195.0       185.220           188000.0   
17657                2023.0       190.0       180.810           142000.0   
17658                2021.0       187.0       174.195           214000.0   
17659                2021.0       186.0       171.990      

## **Seperating datasets**

In [ ]:
y = df['Potential']
y

0        88
1        87
2        85
3        91
4        89
         ..
17655    61
17656    64
17657    56
17658    65
17659    61
Name: Potential, Length: 17660, dtype: int64

In [ ]:
columns_to_add = ['Overall','Contract Valid Until','Height(cm.)','Weight(lbs.)','Release Clause(£)']
x = df[columns_to_add]
x

Overall  Contract Valid Until  Height(cm.)  Weight(lbs.)  \
0           87                2026.0        189.0       180.810   
1           86                2026.0        179.0       152.145   
2           85                2024.0        172.0       152.145   
3           91                2025.0        181.0       154.350   
4           86                2026.0        172.0       149.940   
...        ...                   ...          ...           ...   
17655       48                2027.0        190.0       171.990   
17656       48                2026.0        195.0       185.220   
17657       51                2023.0        190.0       180.810   
17658       50                2021.0        187.0       174.195   
17659       50                2021.0        186.0       171.990   

       Release Clause(£)  
0            157000000.0  
1            155000000.0  
2             97700000.0  
3            198900000.0  
4            154400000.0  
...                  ...  
17655           218000.0  
17656           188000.0  
17657           142000.0  
17658           214000.0  
17659           131000.0  

[17660 rows x 5 columns]

## **Data Splitting**

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state= 100)

x_train

Overall  Contract Valid Until  Height(cm.)  Weight(lbs.)  \
9759        64                2023.0        192.0       189.630   
8559        67                2024.0        183.0       165.375   
15539       53                2021.0        184.0       183.015   
5926        63                2023.0        188.0       165.375   
15755       55                2024.0        188.0       165.375   
...        ...                   ...          ...           ...   
16304       63                2022.0        185.0       171.990   
79          76                2025.0        175.0       154.350   
12119       56                2022.0        182.0       171.990   
14147       65                2023.0        195.0       198.450   
5640        62                2022.0        180.0       171.990   

       Release Clause(£)  
9759            784000.0  
8559            481000.0  
15539           447000.0  
5926            894000.0  
15755           426000.0  
...                  ...  
16304            63000.0  
79            23900000.0  
12119           674000.0  
14147           257000.0  
5640           1300000.0  

[14128 rows x 5 columns]

In [ ]:
x_test

Overall  Contract Valid Until  Height(cm.)  Weight(lbs.)  \
2611        75                2023.0        180.0       171.990   
3824        73                2023.0        181.0       167.580   
6488        60                2021.0        172.0       141.120   
2492        67                2023.0        178.0       154.350   
15468       59                2027.0        192.0       185.220   
...        ...                   ...          ...           ...   
15990       54                2020.0        193.0       198.450   
15395       53                2022.0        185.0       158.760   
7053        66                2022.0        171.0       147.735   
835         72                2025.0        187.0       185.220   
6106        62                2026.0        178.0       160.965   

       Release Clause(£)  
2611           1300000.0  
3824           5700000.0  
6488            313000.0  
2492           1900000.0  
15468          1300000.0  
...                  ...  
15990           131000.0  
15395           385000.0  
7053           4200000.0  
835            3200000.0  
6106           1400000.0  

[3532 rows x 5 columns]

In [ ]:
y_train

9759     65
8559     67
15539    62
5926     65
15755    64
         ..
16304    63
79       80
12119    70
14147    65
5640     73
Name: Potential, Length: 14128, dtype: int64

# **Model Building**

## **Linear Regression**

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

## **Testing the Model**

In [ ]:
y_old_pred = lr.predict(x_train)
y_new_pred = lr.predict(x_test)

## Trying to get the same y values as last time

In [ ]:
y_old_pred

array([70.26947014, 72.86822792, 63.50249058, ..., 65.98349401,
       70.42633844, 68.83063737])

In [ ]:
old_y = y_old_pred.reshape(-1,1)
old_y

array([[70.26947014],
       [72.86822792],
       [63.50249058],
       ...,
       [65.98349401],
       [70.42633844],
       [68.83063737]])

## Checking for the split up x values

In [ ]:
y_new_pred

array([75.78314556, 75.53185195, 68.90047885, ..., 71.84821603,
       74.81345641, 70.66193634])

In [ ]:
new_y = y_new_pred.reshape(-1,1)
new_y

array([[75.78314556],
       [75.53185195],
       [68.90047885],
       ...,
       [71.84821603],
       [74.81345641],
       [70.66193634]])

# **Evaluating the model**

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score

lr_train_mse = mean_squared_error(y_train, y_old_pred)
r2_score_train = r2_score(y_train, y_old_pred)

lr_test_mse = mean_squared_error(y_test,y_new_pred)
r2_score_test = r2_score(y_test,y_new_pred)

print("LR train mean squared error: ",lr_train_mse)
print("LR r2 train: ",r2_score_train)
print("LR train mean squared error: ",lr_test_mse)
print("LR r2 train: ",r2_score_test)

LR train mean squared error:  19.25197168085956
LR r2 train:  0.5437123629516256
LR train mean squared error:  20.104887886468266
LR r2 train:  0.5472246016534781


In [ ]:
lr_results = pd.DataFrame(['LinearRegression',lr_train_mse,r2_score_train,lr_test_mse,r2_score_test]).transpose()
lr_results.columns = ['Methods','Training Mse','Training R2','Test mse','Test r2']
print(lr_results)

            Methods Training Mse Training R2   Test mse   Test r2
0  LinearRegression    19.251972    0.543712  20.104888  0.547225
